package com.myspace.cep_1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Alert implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "ALERT_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "ALERT_ID_SEQ", name = "ALERT_ID_GENERATOR")
    private java.lang.Long id;

    public Alert() {
    }
    
    public Alert(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}